import { createContext } from "react"

import Monster from "../Monsters/Monster"

import { TMonster, TPlayers } from "../../services/server/types"

interface stageContext{
    hpBarFirstMonster: number,
    hpBarSecondMonster: number,
    hpBarThirdMonster: number,
    hpBarFirstEnemyMonster: number,
    hpBarSecondEnemyMonster: number,
    hpBarThirdEnemyMonster: number,
    maxHpBarFirstMonster: number,
    maxHpBarSecondMonster: number,
    maxHpBarThirdMonster: number,
    maxHpBarFirstEnemyMonster: number,
    maxHpBarSecondEnemyMonster: number,
    maxHpBarThirdEnemyMonster: number,
    firstSelectedMonster: TMonster,
    secondSelectedMonster: TMonster,
    thirdSelectedMonster: TMonster,
    firstSelectedEnemyMonster: TMonster,
    secondSelectedEnemyMonster: TMonster,
    thirdSelectedEnemyMonster: TMonster,
    activeMonster: TMonster,
    sQueue: TMonster[],
    stageProps: {
      width: number,
      height: number,
    },
    monster: number[],
    oppMonster: number[],
    buttonClicked: boolean,
    setTime: (time: number) => void,
    setButtonClicked: (buttonClicked: boolean) => void,
    setHpBarFirstEnemyMonster: (hpBarFirstMonsterumber: number) => void,
    setHpBarFirstMonster: (hpBarSecondMonster: number) => void,
    setHpBarSecondEnemyMonster: (hpBarThirdMonster: number) => void,
    setHpBarSecondMonster: (hpBarFirstEnemyMonster: number) => void,
    setHpBarThirdEnemyMonster: (hpBarSecondEnemyMonster: number) => void,
    setHpBarThirdMonster: (hpBarThirdEnemyMonster: number) => void,
    setSQueue: (sQueue: TMonster[]) => void,
    setActiveMonster: (activeMonster: TMonster) => void,
    setQueue: (fightId: number, squeue: number[]) => void,
    fightId: number,
    Queues: number[],
    firstPlayer: TPlayers,
    secondPlayer: TPlayers

  }
  
  export const stageContext = createContext<stageContext>({
    hpBarFirstMonster: 0,
    hpBarSecondMonster: 0,
    hpBarThirdMonster: 0,
    hpBarFirstEnemyMonster: 0,
    hpBarSecondEnemyMonster: 0,
    hpBarThirdEnemyMonster: 0,
    maxHpBarFirstMonster: 0,
    maxHpBarSecondMonster: 0,
    maxHpBarThirdMonster: 0,
    maxHpBarFirstEnemyMonster: 0,
    maxHpBarSecondEnemyMonster: 0,
    maxHpBarThirdEnemyMonster: 0,
    firstSelectedMonster: new Monster,
    secondSelectedMonster: new Monster,
    thirdSelectedMonster: new Monster,
    firstSelectedEnemyMonster: new Monster,
    secondSelectedEnemyMonster: new Monster,
    thirdSelectedEnemyMonster: new Monster,
    activeMonster: new Monster,
    sQueue: [],
    stageProps: {
      width: 0,
      height: 0,
    },
    monster: [],
    oppMonster: [],
    buttonClicked: false,
    setButtonClicked: () => {},
    setTime: () => {},
    setHpBarFirstEnemyMonster: () => {},
    setHpBarFirstMonster: () => {},
    setHpBarSecondEnemyMonster: () => {},
    setHpBarSecondMonster: () => {},
    setHpBarThirdEnemyMonster: () => {},
    setHpBarThirdMonster: () => {},
    setSQueue: () => {},
    setActiveMonster: () => {},
    setQueue: () => {},
    fightId: 0,
    Queues: [],
    firstPlayer: {user_id: 0,
                  opponent_id: 0,
                  monsters: [],
                  monster_opp: []
    },
    secondPlayer: {user_id: 0,
                  opponent_id: 0,
                  monsters: [],
                  monster_opp: []
    }
  })